### PR TITLE
Fix #833 with Dougal.

### LINKED ISSUE #833: Simplification fails on a table containing functions whose type mentions the table index
Reproduction:
```
for i:(Fin 2). \(x:Float). for j:(..i). 1
```

Expected: a value of type `((i:(Fin 2)) => (Float -> (..i) => Int32))`.

Got:
```
> Compiler bug!
> Please report this at github.com/google-research/dex-lang/issues
>
> Leaked local variables:[v1]
```

This happens when trying to differentiate through the LU decomposition, which uses triangular matrices internally.

### PR DESCRIPTION
**Pull request by axch**
The root of the problem is that Dex used to capture lambda-bound
variables during defunctionalization; but that's actually too
conservative, because the argument (unlike anything from the enclosing
environment) will actually be available when the lambda is
reconstructed.

This change avoids doing that, so the return type of the lambda need
no longer be hoisted past its binder, and thereby doesn't trigger the
observed leak error.

Co-authored-by: @dougalm <d.maclaurin@gmail.com>

### CODE REVIEW

**Comment by axch** [comment]
Fixes #833.

**Review by dougalm — APPROVED** [review]

File: src/lib/Simplify.hs [hunk 1]
```diff
@@ -523,53 +525,61 @@ simplifyOp op = case op of
...
+    (lam', Abs b recon) <- simplifyLam lam
     ans <- liftM Var $ emit $ Hof $ For d lam'
     case recon of
       IdentityRecon -> return ans
       LamRecon reconAbs ->
         buildTabLam "i" ixTy \i' -> do
           elt <- tabApp (sink ans) $ Var i'
-          applyReconAbs (sink reconAbs) elt
+          reconAbs' <- applySubst (b @> i') reconAbs
+          applyReconAbs reconAbs' elt
```
Comment (apaszke) [inline src/lib/Simplify.hs:543]: It would be nice if we could avoid substituting the body of `recon` twice (once in `applySubst` and once in `applyReconAbs`). Perhaps we could make `applyReconAbs` run in a `SubstReader`?

File: src/lib/Simplify.hs [hunk 2]
```diff
@@ -359,26 +359,31 @@ simplifyVar v = do
...
+      -> SimplifyM i o (Atom o, Abs LamBinder ReconstructAtom o)
     doSimpLam b body = do
       (Abs b' body', recon) <- simplifyAbs $ Abs b body
       return $! (Lam $ LamExpr b' body', recon)
 
-simplifyBinaryLam :: Emits o => Atom i -> SimplifyM i o (Atom o, ReconstructAtom o)
+type BinaryLamBinder = (PairB LamBinder LamBinder)
+
+simplifyBinaryLam :: Emits o => Atom i
+  -> SimplifyM i o (Atom o, Abs (PairB LamBinder LamBinder) ReconstructAtom o)
```
Comment (apaszke) [inline src/lib/Simplify.hs:378]: nit: use `BinaryLamBInder` here?

**Review by apaszke — APPROVED** [review]

File: src/lib/Simplify.hs (hunk 2 above)
Comment (axch) [reply src/lib/Simplify.hs]: Done.

File: src/lib/Simplify.hs (hunk 1 above)
Comment (axch) [reply src/lib/Simplify.hs:546]: Left a todo note.  I don't know how to do this; want to pair it some time?
